server:
  port: 9000

spring:
    datasource:
        name: test
        url: jdbc:mysql://45.78.57.75:3306/test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Password124
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true