server:
  port: 9000

spring:
  datasource:
          name: test
          url: jdbc:mysql://45.78.57.75:3306/test?useUnicode=true&characterEncoding=UTF-8
          username: root
          password: Password124
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 45.78.57.75
    port: 6379
    password: Password124
#    timeout: 0 #连接超时时间(毫秒)
    pool:
      max-active: 1000  #连接池最大数，负数表示没有限制
      max-wait: -1       #连接池阻塞等待时间，负数表示没有限制
      max-idle: 10
      min-idle: 2


mybatis:
  mapper-locations: classpath:mapping/*.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
cronExpression: 0/10 * * * * ? #每天15:56:45秒运行,只支持6位，不支持最后一位的年
